# Data zijn niet heilig! {#sec-mt3}

---
subtitle: "Over de herkomst, metingen, fouten en dark data"
author: 
  - name: "Gerko Vink"
    orcid: "0000-0001-9767-1924"
    email: g.vink@uu.nl
    affiliations:
      - name: Methodology & Statistics @ Utrecht University
format:
  html:
    number-sections: false
    toc: true
    toc-depth: 3
---

::: callout-tip
## Hoorcollege 18 juni 2026
Vandaag besteden we aandacht aan data. We zullen zien dat data niet altijd te vertrouwen is en dat data ook vaak gezien kan worden als gemaakt bewijs in plaats van enkel neutrale feiten. Ook zullen we potentiele biases leren identificeren. We besteden in dit hoorcollege aandacht aan:

- data provenance: wie heeft de data verzameld, met welk doel en volgens welke procedures?
- het verschil tussen observatie-eenheid, analyse-eenheid, steekproef en doelpopulatie
- variabelen als metingen van begrippen, niet alleen als kolommen in een databestand
- dark data: ontbrekende waarden, nonrespons, onderdekking, verborgen populaties en niet-gemeten confounders
- publieke en surveydata: steekproefontwerp, wegingen, representativiteit, clustering en stratificatie
- het belang van metadata, codeboeken en documentatie
- datakwaliteit als onderdeel van het uiteindelijke onderzoeksantwoord

In het vorige hoorcollege hebben we al stil gestaan bij mogelijke beperkingen. Vandaag gaan we daarom in dat dergelijke beperkingen onderdeel zouden moeten zijn van het onderzoek, en niet enkel een -afterthought- in de discussie van ons onderzoeksverslag.

De slides voor het hoorcollege kunt je [hier vinden](slides/lec-3.html).

:::


## Groepsopdracht

Data biography worksheet maken met de onderstaande velden:

- Naam van het databestand.
- Eigenaar of bron van de data.
- Oorspronkelijk doel van de dataverzameling.
- Observatie-eenheid.
- Doelpopulatie.
- Geobserveerde populatie of steekproef.
- Tijdperiode.
- Steekproef- of selectiemechanisme.
- Wegingen of designvariabelen, indien relevant.
- Belangrijkste variabelen die nodig zijn voor het project.
- Belangrijke ontbrekende waarden of niet-beschikbare variabelen.
- Mogelijke meetproblemen.
- Mogelijke selectie- of dekkingsproblemen.
- Ethische, privacy- of toegangsbeperkingen.
- Waarvoor het databestand geschikt is.
- Welke vragen het databestand niet kan beantwoorden.

1. Dataset Inventory
2. Dark Data diagnose
3. Gebruiksoverzicht van onze data:
 - waarom is de data geschikt of nuttig?
 - wat is de belangrijkste beperking?
 - hoe ondervang ik die beperking?
 
Synthese: Zijn er beperkingen die een verandering in de RQ vereisen?

## Individuele opdracht
1. voortbouwen op technieken geleerd in groepsopdracht
2. maak Data Decision Log aan (morgen gaan vullen)


