# Onzekerheid, aannames en robuustheid {#sec-mt6}

---
subtitle: "Hoe fout mag ons antwoord zijn?"
author: 
  - name: "Gerko Vink"
    orcid: "0000-0001-9767-1924"
    email: g.vink@uu.nl
    affiliations:
      - name: Methodology & Statistics @ Utrecht University
format:
  html:
    number-sections: false
    toc: true
    toc-depth: 3
---

::: callout-tip
## Hoorcollege 23 juni 2026

Vandaag kijken we naar onzekerheid, aannames en robuustheid. Ieder statistisch antwoord hangt af van aannames over de data, de meting, het model en de onderzoekssituatie. In dit college leren we hoe je die aannames zichtbaar kunt maken en hoe je eenvoudige controles kunt plannen om te onderzoeken hoe stevig of robuust je conclusies zijn. We besteden aandacht aan:

- onzekerheid als meer dan alleen $p$-waarden en betrouwbaarheidsintervallen
(- steekproefonzekerheid, meetonzekerheid, modelonzekerheid en missing-data-onzekerheid) --> dag ervoor?
- aannames als brug tussen analyse en conclusie
- bedreigingen voor validiteit, zoals selectiebias, confounding, nonrespons en meetfouten
- het herkennen van te sterke conclusies bij beperkte data
- eenvoudige robuustheids- en sensitiviteitschecks

Ook besteden we aandacht aan verantwoord taalgebruik bij conclusies. Een goed statistisch antwoord zegt niet alleen wat de resultaten laten zien, maar ook onder welke aannames die resultaten betekenisvol zijn.

De slides voor het hoorcollege kun je [hier vinden](slides/lec-6.html).

:::

<!-- ## Groepsopdracht -->
<!-- sceptische reviewer opdracht.  -->

<!-- -> krijg tekst -->
<!-- -> schrijf conclusie -->
<!-- -> geef door + doe review -->
<!-- -> robustness check + suggestie -->
<!-- -> herschrijven conclusie -->

<!-- - hoofconclusie (intended) -->
<!-- - aannames -->
<!-- - grootste bedreiging voor validiteti? -->
<!-- - effect bedreiging op conclusie? -->
<!-- - 1 mogelijke robusstheid of sensitiviteitscheck -->
<!-- - welk resultatt brengt vertrouwen omhoog? -->
<!-- - welk res naar beneden? -->
<!-- - verantwoord rephrasen van conclusie nodig? -->

## Groepsopdracht
De groepsopdracht [staat hier](opdracht/Groepsopdracht6.html).

## Individuele opdracht
Overmorgen gaan we in gesprek over het presenteren van je eigen werk. Op vrijdag presenteer je je eigen project aan de groep. Gebruik de resterende tijd vandaag om je (voorlopige) resultaten en conclusies nog eens aan te scherpen. Begin alvast met het maken van een presentatie of de opzet daarvan en denk na over een goede manier om je resultaten en conclusie te verwoorden of te presernteren. 
