# Reproduceerbare onderzoeksarchieven {#sec-mt4}

---
subtitle: "Hoe kom ik van ruwe data tot een keten van bewijs?"
author: 
  - name: "Gerko Vink"
    orcid: "0000-0001-9767-1924"
    email: g.vink@uu.nl
    affiliations:
      - name: Methodology & Statistics @ Utrecht University
format:
  html:
    number-sections: false
    toc: true
    toc-depth: 3
---

::: callout-tip
## Hoorcollege 19 juni 2026
Vandaag kijken we naar reproduceerbaar onderzoek. We leren hoe we er voor kunnen zorgen dat de route van ruwe data naar eindrapport transparant, controleerbaar en begrijpelijk is? We behandelen reproduceerbaarheid niet alleen als tecnhische netheid, maar als onderdeel van wetenschappelijke integriteit en professioneel statistisch werk. We besteden aandacht aan:

- wat een reproduceerbaar onderzoeksarchief is
- waarom transparantie belangrijk is voor geloofwaardigheid, samenwerking en begeleiding
- hoe een goede projectstructuur helpt om fouten te vinden en keuzes te verantwoorden
- welke onderdelen minimaal in een onderzoeksarchief aanwezig moeten zijn
- het verschil tussen ruwe data, opgeschoonde data, scripts, output, rapport en presentatie
- het belang van een README, (evt datatoegangsnotitie), codeboek en beslislogboek
- principes voor een transparante workflow, zoals het niet overschrijven van ruwe data
- verklaren welke invloed AI heeft gehad in het project

Ook besteden we aandacht aan het idee dat reproduceerbaarheid niet perfect hoeft te zijn om waardevol te zijn. Het belangrijkste is traceerbaarheid: wat is er gedaan, waarom is dat gedaan, waar staat het beschreven, en waar komt de output in het rapport vandaan?

De slides voor het hoorcollege kunt je [hier vinden](slides/lec-4.html).
:::

## Groepsopdracht
De groepsopdracht [staat hier](opdracht/Groepsopdracht4.html).

## Individuele opdracht
Gebruik nu het geleerde om een eigen structuur voor je onderzoeksarchief te maken. Je kunt dit doen door een nieuwe map aan te maken en daarin de volgende onderdelen te plaatsen:

- Een duidelijke mapstructuur. Let op: je hoeft niet alles te vullen, maar maak wel de mappen aan. Bijvoorbeeld:

```text
clean_project/
├── README.md
├── license.txt
├── AI_use.md
├── data/
│   ├── raw/
│   │   └── suriname_households_raw.csv
│   └── processed/
│       └── suriname_households_clean.csv
├── documentation/
|   ├── data_decision_log.md
│   └── codebook.md
├── code/
│   ├── 01_clean_data.R
│   └── 02_make_table.R
├── output/
│   ├── tables/
│   │   └── table_household_summary.csv
│   └── figures/
│       └── fig_income_by_district.png
└── report/
    └── short_report.docx
    
```

Je kunt dit altijd later aanpassen en uitbreiden als blijkt dat de structuur die je tot nu toe hebt aangehouden niet meer toereikend is. Het is echter wel verstandig om zo spoedig mogelijk in een duidelijke structuur te werken, zodat je niet later voor verrassingen komt te staan. We hebben in de groepsopdracht gezien hoe lastig het kan zijn om de structuur achteraf nog te bepalen. 

- maak een beslislogboek (data decision log) om te documenteren welke keuzes je hebt gemaakt bij het verkrijgen van data, het opschonen van data, en het analyseren van data. Dit logboek helpt niet alleen om transparant te zijn over je keuzes, maar ook om later terug te kunnen kijken op waarom bepaalde beslissingen zijn genomen.
- maak codeboek als het er nog niet is.
- maak een README waarin je de structuur van je project uitlegt.
- maak een AI log waarin je aangeeft welke invloed AI heeft gehad in het project en (indien van toepassing) hoe je AI hebt gebruikt. Bijvoorbeeld met een logboek waarin de gebruikte prompts staan. 

> **TIP:** Je kunt hiervoor ook de beschrijving uit de individuele opdracht bij de tweede bijeenkomst gebruiken. 
